#!/bin/sh
#
# This script is a temporary solution to keep the Android module `KTPinBlock` of project `KTPinBlockSample` to be in sync with the KMM project `ktpinblock`.
# It has some drawbacks, e.g. deleted files will not be reflected. But before putting more efforts in improving it, a bigger decision should be made first.
#
# After evaluation the KMM approach, eventually we should either remove `KTPinBlock`, and `KTPinBlockSample` will consume the `AAR` file generated by `ktpinblock` directly;
# or we give up the KMM approach and build an iOS framework based on Swift.
#
cp -r KTPinBlockSample/KTPinBlock/src/main/java/org/superarts/ktpinblock ktpinblock/ktpinblock/src/commonMain/kotlin/org/superarts/